### ISSUE TITLE
Can't decrypt some JP V3 files that are ABLE to read by official client

### ISSUE THREAD

**Issue by NijiharaTsubasa** [MikuAuahDark/HonokaMiku#8]
Here are some files generated by my encrypt script
(link removed)
**Official 4.1 engine is able to read them**
but HonokaMiku and SIF_Win32 can't
````
$ ./HonokaMiku.exe lives/moment_ring_ex/clear.ogg
HonokaMiku. Universal LL!SIF game files decrypter
Auto-detecting: JP (Version 3) game file
Error: Name sum counter doesn't match
````

**Comment by MikuAuahDark** [comment]
https://github.com/DarkEnergyProcessor/HonokaMiku/blob/f14a3f0850395df2d17bb9533a5641f97bd94b0a/src/V3_Decrypter.cc#L50-L68

There's `name_sum` and `expected_name_sum` check over there which actually, official client doesn't do (damn KLab add it please). However, files encrypted officially by KLab always passes that check, so you have to modify your encrypt script to comply with it. Files which is V3-encrypted by HonokaMiku also calculate and uses correct name sum counter so that it passes the check.

The algorithm to check the name counter is simple

1. Store the sum of the basename ASCII char value in a variable

2. Add it by initial value of the name sum counter. It's different for each game, but for JP, it's 500

3. Compare the value by the value specificed in the header (offset 10-11, big endian).

If it match, then HonokaMiku will decrypt it nicely, but if it doesn't, HonokaMiku will throw error as you can see right now.

Marked as wontfix.

**Comment by NijiharaTsubasa** [comment]
Well
I think a decryptor should at least be fully compatible with the official client (if a file can be read by official client, then it should be able to be decrypted by a decrypter)
So a warning here may be better?

**Comment by MikuAuahDark** [comment]
No. I'll keep it like that. I think that's a feature.

You can compile HonokaMiku by yourself with those checks disabled and you'll good.
